import { randomElement } from "../../common/util";
import type { Asset } from "../../common/orders_types";

export function randomAsset(): Asset {
    const name = randomElement(assetNames);
    const quantity = Math.floor(Math.random() * 100) + 1;
    return { name, quantity };
}

const assetNames: string[] = [
    "Apple Inc. (AAPL)",
    "Microsoft Corporation (MSFT)",
    "Amazon.com, Inc. (AMZN)",
    "Tesla, Inc. (TSLA)",
    "Alphabet Inc. Class A (GOOGL)",
    "Meta Platforms, Inc. (META)",
    "Berkshire Hathaway Inc. (BRK.B)",
    "Johnson & Johnson (JNJ)",
    "JPMorgan Chase & Co. (JPM)",
    "Visa Inc. (V)",
    "Nvidia Corporation (NVDA)",
    "Procter & Gamble Co. (PG)",
    "The Coca-Cola Company (KO)",
    "Exxon Mobil Corporation (XOM)",
    "Pfizer Inc. (PFE)",
    "Wells Fargo & Company (WFC)",
    "Chevron Corporation (CVX)",
    "PepsiCo, Inc. (PEP)",
    "Walmart Inc. (WMT)",
    "Intel Corporation (INTC)",
    "U.S. Treasury Bond 10-Year (T10Y)",
    "U.S. Treasury Bond 30-Year (T30Y)",
    "German Government Bond 10-Year (Bund)",
    "UK Government Bond 10-Year (Gilt)",
    "Japan Government Bond 10-Year (JGB)",
    "Apple Inc. Corporate Bond 10-Year",
    "Microsoft Corporation Corporate Bond 10-Year",
    "Amazon.com, Inc. Corporate Bond 10-Year",
    "Tesla, Inc. Corporate Bond 10-Year",
    "Google Corporate Bond 10-Year",
    "Gold (XAU)",
    "Silver (XAG)",
    "Crude Oil (WTI)",
    "Brent Crude Oil (Brent)",
    "Natural Gas (NG)",
    "Copper (HG)",
    "Corn (C)",
    "Soybeans (S)",
    "Wheat (W)",
    "Coffee (KC)",
    "Platinum (PL)",
    "Palladium (PA)",
    "Aluminum (ALI)",
    "Iron Ore (Fe)",
    "Cotton (CT)",
    "Sugar (SB)",
    "Live Cattle (LC)",
    "Lean Hogs (LH)",
    "Lumber (LBS)",
    "Cocoa (CC)",
    "SPDR S&P 500 ETF (SPY)",
    "Vanguard Total Stock Market ETF (VTI)",
    "Invesco QQQ Trust (QQQ)",
    "iShares Russell 2000 ETF (IWM)",
    "Vanguard FTSE Emerging Markets ETF (VWO)",
    "iShares MSCI EAFE ETF (EFA)",
    "iShares U.S. Treasury Bond ETF (GOVT)",
    "SPDR Gold Shares (GLD)",
    "iShares Silver Trust (SLV)",
    "Energy Select Sector SPDR Fund (XLE)",
    "American Tower Corporation (AMT)",
    "Prologis, Inc. (PLD)",
    "Public Storage (PSA)",
    "Digital Realty Trust, Inc. (DLR)",
    "Equity Residential (EQR)",
    "Welltower Inc. (WELL)",
    "Simon Property Group, Inc. (SPG)",
    "Realty Income Corporation (O)",
    "AvalonBay Communities, Inc. (AVB)",
    "Boston Properties, Inc. (BXP)",
    "Vanguard 500 Index Fund (VFINX)",
    "Fidelity 500 Index Fund (FXAIX)",
    "T. Rowe Price Blue Chip Growth Fund (TRBCX)",
    "Vanguard Total Bond Market Index Fund (VBMFX)",
    "American Funds The Growth Fund of America (AGTHX)",
    "PIMCO Total Return Fund (PTTRX)",
    "Fidelity Contrafund (FCNTX)",
    "Vanguard Wellington Fund (VWELX)",
    "Dodge & Cox Stock Fund (DODGX)",
    "T. Rowe Price Equity Income Fund (PRFDX)",
    "U.S. Dollar (USD)",
    "Euro (EUR)",
    "British Pound (GBP)",
    "Japanese Yen (JPY)",
    "Swiss Franc (CHF)",
    "Australian Dollar (AUD)",
    "Canadian Dollar (CAD)",
    "Chinese Yuan (CNY)",
    "Indian Rupee (INR)",
    "Brazilian Real (BRL)"
]