advertised-address = "http://127.0.0.1:15122/"
tokio-console-bind-address = "0.0.0.0:16669"
disable-prometheus = true
rocksdb-total-memory-size = "2.0 GB"

[metadata-client]
addresses = ["http://127.0.0.1:15122/"]

[admin]
bind-address = "0.0.0.0:19070"

[admin.query-engine]
pgsql-bind-address = "0.0.0.0:19071"

[ingress]
bind-address = "0.0.0.0:18080"
